aliases:
  nba:
    boston celtics: [bos, boston, celtics]
    cleveland cavaliers: [cle, cavs, cavaliers, cleveland]
    detroit pistons: [det, detroit, pistons]
    los angeles lakers: [lal, la lakers, lakers]
    minnesota timberwolves: [min, wolves, timberwolves]
    oklahoma city thunder: [okc, thunder]
    san antonio spurs: [sa, sas, spurs]
  nfl:
    kansas city chiefs: [kc, chiefs]
    new york jets: [nyj, jets]
    washington commanders: [was, commanders]
  mlb:
    baltimore orioles: [bal, orioles]
    cincinnati reds: [cin, reds]
    cleveland guardians: [cle, guardians]
    detroit tigers: [det, tigers]
    miami marlins: [mia, marlins]
    milwaukee brewers: [mil, brewers]
    minnesota twins: [min, twins]
    new york yankees: [nyy, ny yankees, yankees]
    oakland athletics: [ath, athletics, a's]
    philadelphia phillies: [phi, phillies]
    pittsburgh pirates: [pit, pirates]
    san francisco giants: [sf, giants]
    tampa bay rays: [tb, rays]
    toronto blue jays: [tor, blue jays]
    washington nationals: [wsh, nationals]
  nhl:
    boston bruins: [bos, bruins]
    buffalo sabres: [buf, sabres]
    carolina hurricanes: [car, hurricanes]
    new york rangers: [nyr, rangers]
    toronto maple leafs: [tor, maple leafs, leafs]
  tennis:
    carlos alcaraz: [alcaraz]
    jannik sinner: [sinner]
    aryna sabalenka: [sabalenka]
    iga swiatek: [swiatek]
